name: project-blackbox
services:
- name: backend
  source_dir: /
  github:
    repo: SingSongScreamAlong/blackbox
    branch: master
  run_command: python server.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: ENVIRONMENT
    value: production
  - key: PORT
    value: "8080"
